// teacher/config/en.js
export const teacherEn = {
  brand: "UNI Core",
  brandShort: "Teacher Portal",
  roleLabel: "Teacher",

  sidebar: {
    dashboard:    "Dashboard",
    classes:      "Classes",
    exams:        "Exams",
    questionBank: "Question Bank",
    submissions:  "Submissions",
    results:      "Results",
    appeals:      "Grade Appeals",
    resources:    "Resources",
    profile:      "Profile",
    collapse:     "Collapse sidebar",
    expand:       "Expand sidebar",

    sections: {
      main:    "Main",
      academic:"Academic",
      manage:  "Manage",
    },
  },

  dashboard: {
    greeting:        (name) => `Good morning, ${name}`,
    greetingAfternoon: (name) => `Good afternoon, ${name}`,
    greetingEvening:   (name) => `Good evening, ${name}`,
    greetingDefault: "Good morning",
    subtitle:        "Here's what's happening in your classes today.",
    overview:        "Overview",
    myClasses:       "My Classes",
    viewAll:         "View all",
    noClasses:       "No classes assigned yet.",
    recentEnrollments: "Recent Enrollments",
    noEnrollments:   "No new enrollments this week.",
    scheduledClasses:"Scheduled Classes",
    noScheduled:     "No scheduled classes found.",
    onlineAndSynced: "Online and Synced",

    stats: {
      totalClasses:   "Total Classes",
      totalStudents:  "Total Students",
      upcomingExams:  "Scheduled",
      pendingGrading: "Pending Grading",
      nextExam:       "Next",
      dueSoon:        "Check assignments",
      thisSemester:   "this semester",
      thisWeek:       "this week",
      active:         "active",
      acrossAll:      "Across all classes",
      classesWithSchedule: "Classes with schedule",
    },

    quickActions:     "Quick Actions",
    createClass:      "Create Class",
    createExam:       "Create Exam",
    uploadResource:   "Upload Resource",

    upcomingExams:    "Upcoming Exams",
    newExam:          "+ New Exam",
    recentActivity:   "Recent Activity",
    pendingGrading:   "Pending Grading",

    noExams:         "No upcoming exams",
    noActivity:      "No recent activity",
    noPending:       "Nothing to grade — you're all caught up!",

    left:            "left",
    due:             "Due",
    viewProfile:     "My Profile",
  },

  classes: {
    teaching:       "Teaching",
    myClasses:      "My Classes",
    loading:        "Loading…",
    classesAssigned:(count) => `${count} class${count !== 1 ? "es" : ""} assigned to you`,
    searchPlaceholder: "Search classes…",
    retry:          "Retry",
    noMatch:        "No classes match your search.",
    noClasses:      "No classes assigned yet.",
    clearSearch:    "Clear search",
    students:       "students",
    viewClass:      "View class",
    semester:       "Semester",
    credits:        "cr",
  },

  classDetail: {
    backToClasses:   "Back to Classes",
    retry:           "Retry",
    roster:          "Roster",
    loadingStudents: "Loading students…",
    enrolledStudents:(count) => `${count} enrolled student${count !== 1 ? "s" : ""}`,
    searchStudents:  "Search students…",
    noMatch:         "No students match your search.",
    noStudents:      "No students enrolled yet.",
    clearSearch:     "Clear search",
    showing:         (filtered, total) => `Showing ${filtered} of ${total} students`,
    tableStudent:    "Student",
    tableId:         "ID",
    tableDepartment: "Department",
    tableSemester:   "Semester",
    tableContact:    "Contact",
    tableStatus:     "Status",
    tableClaimed:    "Claimed",
    credits:         "credits",
    enrolled:        "enrolled",
  },

  questionBank: {
    title:          "Question Bank",
    subtitle:       "Save and reuse questions across multiple exams and courses.",
    searchPlaceholder: "Search questions…",
    addQuestion:    "Add Question",
    allTypes:       "All Types",
    allDifficulty:  "All Difficulty",
    easy:           "Easy",
    medium:         "Medium",
    hard:           "Hard",
    noQuestions:    "No questions in the bank yet.",
    addFirst:       "Add your first question to get started.",
    marks:          "marks",
    editQuestion:   "Edit",
    deleteQuestion: "Delete",
    questionText:   "Question text",
    questionType:   "Question type",
    difficulty:     "Difficulty",
    save:           "Save Question",
    cancel:         "Cancel",
    questionAdded:  "Question added to bank!",
    questionUpdated:"Question updated!",
    questionDeleted:"Question deleted.",
    confirmDelete:  "Are you sure you want to delete this question?",
  },

  submissions: {
    title:          "Submissions",
    subtitle:       "Review student submissions, mark assignments, and leave feedback.",
    searchPlaceholder: "Search by student or exam…",
    noSubmissions:  "No submissions yet.",
    waitingText:    "Submissions will appear here once students complete their exams.",
    student:        "Student",
    exam:           "Exam",
    score:          "Score",
    status:         "Status",
    submittedAt:    "Submitted",
    viewDetails:    "View Details",
    gradeNow:       "Grade",
    autoGraded:     "Auto-graded",
    manualReview:   "Manual Review",
    submitted:      "Submitted",
    points:         "pts",
    violations:     "violations",
    feedback:       "Feedback",
    feedbackPlaceholder: "Enter feedback for the student…",
    saveFeedback:   "Save Feedback",
  },

  results: {
    title:          "Results & Analytics",
    subtitle:       "View class performance, grade distributions, and export reports.",
    totalExams:     "Total Exams",
    activeExams:    "Active Exams",
    totalSubmissions:"Total Submissions",
    avgScore:       "Average Score",
    securityEvents: "Security Events",
    recentSubmissions:"Recent Submissions",
    noSubmissions:  "No submissions yet",
    securityLog:    "Security Events",
    noSecurity:     "No security violations logged",
    exportResults:  "Export Results",
    student:        "Student",
    exam:           "Exam",
    score:          "Score",
    status:         "Status",
  },

  resources: {
    title:          "Resources",
    subtitle:       "Upload lecture notes, slides, PDFs, and other course materials.",
    searchPlaceholder: "Search resources…",
    uploadResource: "Upload Resource",
    noResources:    "No resources uploaded yet.",
    uploadFirst:    "Upload your first resource to share with students.",
    fileName:       "File Name",
    category:       "Category",
    allCategories:  "All Categories",
    lectures:       "Lectures",
    assignments:    "Assignments",
    references:     "References",
    slides:         "Slides",
    other:          "Other",
    uploadedAt:     "Uploaded",
    fileSize:       "Size",
    download:       "Download",
    deleteResource: "Delete",
    resourceUploaded:"Resource uploaded!",
    resourceDeleted: "Resource deleted.",
    selectFile:     "Select file",
    dropHere:       "or drag and drop here",
    maxSize:        "Max file size: 50MB",
    uploading:      "Uploading…",
    resourceTitle:  "Resource title",
    titlePlaceholder:"e.g. Week 3 Lecture Notes",
    cancel:         "Cancel",
    save:           "Upload",
  },

  profile: {
    title:          "Profile",
    subtitle:       "Update your personal information and account settings.",
    personalInfo:   "Personal Information",
    fullName:       "Full Name",
    email:          "Email",
    department:     "Department",
    phone:          "Phone",
    bio:            "Bio",
    bioPlaceholder: "Tell your students about yourself…",
    changePassword: "Change Password",
    currentPassword:"Current Password",
    newPassword:    "New Password",
    confirmPassword:"Confirm Password",
    updateProfile:  "Update Profile",
    updatePassword: "Update Password",
    profileUpdated: "Profile updated!",
    passwordUpdated:"Password updated!",
    passwordMismatch:"Passwords do not match.",
    accountInfo:    "Account Information",
    memberSince:    "Member since",
    lastLogin:      "Last login",
    status:         "Status",
    active:         "Active",
  },

  common: {
    view:      "View",
    edit:      "Edit",
    delete:    "Delete",
    cancel:    "Cancel",
    save:      "Save",
    create:    "Create",
    publish:   "Publish",
    back:      "Back",
    next:      "Next",
    noResults: "No results found",
    loading:   "Loading…",
    online:    "Online",
    scheduled: "Scheduled",
    draft:     "Draft",
    search:    "Search…",
    signOut:   "Sign Out",
    comingSoon:"Coming Soon",
  },
};