// teacher/config/so.js
export const teacherSo = {
  brand: "Uni Core",
  brandShort: "Xarunta Macallinka",
  roleLabel: "Macallin",

  sidebar: {
    dashboard:    "Bogga Hore",
    classes:      "Fasallada",
    exams:        "Imtixaannada",
    questionBank: "Xafiiska Su'aalaha",
    submissions:  "Xogta La Gudbiyay",
    results:      "Natiijooyinka",
    appeals:      "Dacwadaha Darajooyinka",
    resources:    "Agabka",
    profile:      "Xogta Shakhsiga",
    collapse:     "Xidh xagga",
    expand:       "Fur xagga",

    sections: {
      main:    "Ugu Muhiimsan",
      academic:"Waxbarasho",
      manage:  "Maarayn",
    },
  },

  dashboard: {
    greeting:          (name) => `Subax wanaagsan, ${name}`,
    greetingAfternoon: (name) => `Galab wanaagsan, ${name}`,
    greetingEvening:   (name) => `Fiid wanaagsan, ${name}`,
    greetingDefault: "Subax wanaagsan",
    subtitle:        "Waa kan waxa ka socda fasalladaada maanta.",
    overview:        "Guud ahaan",
    myClasses:       "Fasalladayda",
    viewAll:         "Eeg dhammaan",
    noClasses:       "Wali fasal laguma meelaysan.",
    recentEnrollments: "Diiwaangelintii Dhawaan",
    noEnrollments:   "Diiwaangelin cusub usbuucan ma jirto.",
    scheduledClasses:"Fasallada La Qorsheeyay",
    noScheduled:     "Fasal la qorsheeyay lama helin.",
    onlineAndSynced: "Online wuu ku jiraa",

    stats: {
      totalClasses:   "Wadarta Fasallada",
      totalStudents:  "Wadarta Ardayda",
      upcomingExams:  "La Qorsheeyay",
      pendingGrading: "Sugaya Darajynta",
      nextExam:       "Xiga",
      dueSoon:        "Hubi howlaha",
      thisSemester:   "xilligaan",
      thisWeek:       "todobaadkan",
      active:         "firfircoon",
      acrossAll:      "Dhammaan fasallada",
      classesWithSchedule: "Fasallada jadwalkooda leh",
    },

    quickActions:     "Ficilada Degdegga",
    createClass:      "Samee Fasal",
    createExam:       "Samee Imtixaan",
    uploadResource:   "Geli Agab",

    upcomingExams:    "Imtixaannada Soo Socda",
    newExam:          "+ Imtixaan Cusub",
    recentActivity:   "Dhaqdhaqaaqa Dhawaan",
    pendingGrading:   "Sugaya Darajynta",

    noExams:         "Imtixaan soo socda ma jiro",
    noActivity:      "Dhaqdhaqaaq dhawaan ma jiro",
    noPending:       "Waxba ma sugin — wax walba aad u samaysay!",

    left:            "haray",
    due:             "Dhammaadka",
    viewProfile:     "Profile-kayga",
  },

  classes: {
    teaching:       "Waxbarid",
    myClasses:      "Fasalladayda",
    loading:        "Waa la rarayaa…",
    classesAssigned:(count) => `${count} fasal${count !== 1 ? "o" : ""} laguu meelayay`,
    searchPlaceholder: "Ka raadi fasallada…",
    retry:          "Dib u isku day",
    noMatch:        "Fasal la raadiyay lama helin.",
    noClasses:      "Wali fasal laguma meelaysan.",
    clearSearch:    "Nadiifi raadinta",
    students:       "arday",
    viewClass:      "Eeg fasalka",
    semester:       "Xilliyeed",
    credits:        "dh",
  },

  classDetail: {
    backToClasses:   "Ku laabo Fasallada",
    retry:           "Dib u isku day",
    roster:          "Liiska Ardayda",
    loadingStudents: "Ardayda waa la rarayaa…",
    enrolledStudents:(count) => `${count} arday${count !== 1 ? "" : ""} oo diiwaangashan`,
    searchStudents:  "Ka raadi ardayda…",
    noMatch:        "Arday la raadiyay lama helin.",
    noStudents:      "Wali arday lama diiwaan gelin.",
    clearSearch:     "Nadiifi raadinta",
    showing:         (filtered, total) => `La muujinayo ${filtered} ka mid ah ${total} arday`,
    tableStudent:    "Ardayga",
    tableId:         "ID-ga",
    tableDepartment: "Qaybta",
    tableSemester:   "Xilliyeedka",
    tableContact:    "Xiriirka",
    tableStatus:     "Xaaladda",
    tableClaimed:    "La xaqiijiyay",
    credits:         "dhibcood",
    enrolled:        "diiwaangashan",
  },

  questionBank: {
    title:          "Xafiiska Su'aalaha",
    subtitle:       "Kaydi oo dib u isticmaal su'aalaha imtixaannada iyo koorsaskaaga.",
    searchPlaceholder: "Ka raadi su'aalaha…",
    addQuestion:    "Ku dar Su'aal",
    allTypes:       "Noocyada Dhammaan",
    allDifficulty:  "Culus-fududayn Dhammaan",
    easy:           "Fudud",
    medium:         "Dhexdhexaad",
    hard:           "Adag",
    noQuestions:    "Wali su'aal kama jirto xafiiska.",
    addFirst:       "Ku dar su'aashaada ugu horeysa si aad u bilowdo.",
    marks:          "dhibcood",
    editQuestion:   "Wax ka beddel",
    deleteQuestion: "Tirtir",
    questionText:   "Qoraalka su'aasha",
    questionType:   "Nooca su'aasha",
    difficulty:     "Culus-fududaynta",
    save:           "Kaydi Su'aasha",
    cancel:         "Jooji",
    questionAdded:  "Su'aasha waa lagu daray xafiiska!",
    questionUpdated:"Su'aasha waa la cusboonaysiiyay!",
    questionDeleted:"Su'aasha waa la tirtiray.",
    confirmDelete:  "Ma hubtaa inaad tirtirto su'aashaan?",
  },

  submissions: {
    title:          "Xogta La Gudbiyay",
    subtitle:       "Eeg jawaabaha ardayda, darajee howlaha, oo faallo ku bixi.",
    searchPlaceholder: "Ku raadi ardayga ama imtixaanka…",
    noSubmissions:  "Wali jawaab lama gudbin.",
    waitingText:    "Jawaabaha waxay halkan ku soo muuqan doonaan marka ardaydu imtixaankooda dhammeeyaan.",
    student:        "Ardayga",
    exam:           "Imtixaanka",
    score:          "Dhibcaha",
    status:         "Xaaladda",
    submittedAt:    "La gudbiyay",
    viewDetails:    "Eeg Faahfaahinta",
    gradeNow:       "Darajee",
    autoGraded:     "Si toos ah loo darajeyay",
    manualReview:   "Dib u eegis gacmeed",
    submitted:      "La gudbiyay",
    points:         "dh",
    violations:     "xadgudubyada",
    feedback:       "Faallo",
    feedbackPlaceholder: "Faallo u qor ardayga…",
    saveFeedback:   "Kaydi Faalada",
  },

  results: {
    title:          "Natiijooyinka & Falanqaynta",
    subtitle:       "Eeg waxqabadka fasalka, qaybinta darajooyinka, oo dhoofi warbixinnada.",
    totalExams:     "Wadarta Imtixaannada",
    activeExams:    "Imtixaannada Firfircoon",
    totalSubmissions:"Wadarta Jawaabaha",
    avgScore:       "Celceliska Dhibcaha",
    securityEvents: "Dhacdooyinka Amaanka",
    recentSubmissions:"Jawaabaha Dhawaan",
    noSubmissions:  "Wali jawaab lama gudbin",
    securityLog:    "Dhacdooyinka Amaanka",
    noSecurity:     "Xadgudub amaan ah lama qorin",
    exportResults:  "Dhoofi Natiijooyinka",
    student:        "Ardayga",
    exam:           "Imtixaanka",
    score:          "Dhibcaha",
    status:         "Xaaladda",
  },

  resources: {
    title:          "Agabka",
    subtitle:       "Geli cashar qoraallada, slides-yada, PDF-yada, iyo agab kale oo koorsadaada ah.",
    searchPlaceholder: "Ka raadi agabka…",
    uploadResource: "Geli Agab",
    noResources:    "Wali agab lama gelin.",
    uploadFirst:    "Geli agabkaaga ugu horreeya si aad ardayda ula wadaagto.",
    fileName:       "Magaca faylka",
    category:       "Qaybta",
    allCategories:  "Qaybaha Dhammaan",
    lectures:       "Casharrada",
    assignments:    "Howlaha",
    references:     "Tixraacyada",
    slides:         "Slides",
    other:          "Kuwa kale",
    uploadedAt:     "La geliyay",
    fileSize:       "Baaxadda",
    download:       "Soo Degso",
    deleteResource: "Tirtir",
    resourceUploaded:"Agabka waa la geliyay!",
    resourceDeleted: "Agabka waa la tirtiray.",
    selectFile:     "Dooro faylka",
    dropHere:       "ama halkan ku soo jiid",
    maxSize:        "Baaxadda ugu badan: 50MB",
    uploading:      "Waa la gelinayaa…",
    resourceTitle:  "Cinwaanka agabka",
    titlePlaceholder:"Tusaale: Casharka 3-aad ee Qoraalka",
    cancel:         "Jooji",
    save:           "Geli",
  },

  profile: {
    title:          "Profile-ka",
    subtitle:       "Cusboonaysii macluumaadkaaga shakhsiga iyo dejinta akoonkaaga.",
    personalInfo:   "Macluumaadka Shakhsiga",
    fullName:       "Magaca Buuxa",
    email:          "Iimeelka",
    department:     "Qaybta",
    phone:          "Telefoonka",
    bio:            "Ku saabsan",
    bioPlaceholder: "U sheeg ardaydaada waxa ku saabsan…",
    changePassword: "Beddel Erayga Sirta ah",
    currentPassword:"Erayga Sirta ah ee Hadda",
    newPassword:    "Erayga Sirta ah ee Cusub",
    confirmPassword:"Xaqiiji Erayga Sirta ah",
    updateProfile:  "Cusboonaysii Profile-ka",
    updatePassword: "Cusboonaysii Erayga Sirta ah",
    profileUpdated: "Profile-ka waa la cusboonaysiiyay!",
    passwordUpdated:"Erayga sirta ah waa la beddelay!",
    passwordMismatch:"Labada eray sir isku mid maaha.",
    accountInfo:    "Macluumaadka Akoonka",
    memberSince:    "Xubin ilaa",
    lastLogin:      "Gelitaankii ugu dambeyay",
    status:         "Xaaladda",
    active:         "Firfircoon",
  },

  common: {
    view:      "Arag",
    edit:      "Wax ka beddel",
    delete:    "Tirtir",
    cancel:    "Jooji",
    save:      "Keydi",
    create:    "Samee",
    publish:   "Baahiso",
    back:      "Dib",
    next:      "Xiga",
    noResults: "Wax lama helin",
    loading:   "Waa la rarayaa…",
    online:    "Online",
    scheduled: "La qorsheeyay",
    draft:     "Qodob",
    search:    "Raadi…",
    signOut:   "Ka bax",
    comingSoon:"Dhowaan wuu imanayaa",
  },
};